const { user_data, newCollection, addTask, dropCollection, deleteTask, createUser, markDone, editTask, renameCollection } = require('../Controllers/AuthController')
const { verifyToken } = require('../Middlewares/verifyTokenMiddleware')
// const userVerification=require('../Middlewares/AuthMiddleware')
const router = require('express').Router()

// router.post('/signup',signUp)
// router.post('/login',login)
// router.post('/logout',logout)
// router.get('/checkLoggedIn',checkLoggedIn)
router.post('/dashboard', verifyToken, user_data)
router.post('/newCollection', verifyToken, newCollection)
router.post('/addTask', verifyToken, addTask)
router.put('/dropCollection', verifyToken, dropCollection)
router.put('/renameCollection', verifyToken, renameCollection)
router.post('/deleteTask', verifyToken, deleteTask)
router.post('/createUser', verifyToken, createUser)
router.post('/markDone', verifyToken, markDone)
router.post('/editTask', verifyToken, editTask)

module.exports = router